# Orbit definitions with names and labels (colors have no effect by default waybar only takes name(text) and label(alt) )
orbits:
  - name: "alpha"
    label: "α"
    color: "#BC83F9"
  - name: "beta"
    label: "β"
    color: "#F97583"
  - name: "gamma"
    label: "γ"
    color: "#85E89D"
  - name: "delta"
    label: "δ"
    color: "#FFAB70"
  - name: "epsilon"
    label: "ε"
    color: "#FFAB70"
  - name: "zeta"
    label: "ζ"
    color: "#FFAB70"
  - name: "theta"
    label: "η"
    color: "#FFAB70"
  - name: "iota"
    label: "ι"
    color: "#FFAB70"

# Module definitions with focus rules
modules:
  code:
    focus:
      match: "class:^code$"
      cmd: ["code"]
    seed:
      - match: "class:^code$"
        cmd: ["code"]
      - match: "class:^(ghostty|Alacritty|kitty)$"
        cmd: ["ghostty"]
  gfx:
    focus:
      match: "class:^(Firefox|zen)$"
      cmd: ["zen-browser"]
    seed:
      - match: "class:^(Firefox|zen)$"
        cmd: ["zen-browser"]
      - match: "class:^Gimp$"
        cmd: ["gimp"]
  comm:
    focus:
      match: "class:^Thunderbird$"
      cmd: ["thunderbird"]
    seed:
      - match: "class:^Thunderbird$"
        cmd: ["thunderbird"]
      # - match: "class:^TelegramDesktop$"
      #   cmd: ["telegram-desktop"]
  media:
    focus:
      match: "class:^(mpv)$"
      cmd: ["mpv"]
  surf:
    focus:
      match: "class:^zen"
      cmd: ["zen-browser"]

defaults:
  float: false
  move: true

orbit:
  switch_preference: last-active-first
